version: "2"

services:

  # ドキュメントを生成する HUGO が動いているコンテナ
  docs:
    container_name: docs
    build: ./server/docs
    env_file: .env
    ports:
      - "${PREVIEW_SERVER_PORT}:1313"
    volumes:
      - ./hugo/common-themes:/usr/local/docs/common-themes
      - ./hugo/default-config.toml:/usr/local/docs/default-config.toml
