baseURL = "https://framelunch.github.io/docs/"
publishDir = "docs"
languageCode = "en"
defaultContentLanguage = "en"
title = "Docs"
theme = "default"
enableEmoji = "true"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  autolink = "enabled"

[params]
  themeVariant = "red"
